language: python
dist: xenial

python:
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - yarn add danger       # install danger-js
  - pip install pipenv    # install pipenv
  - pipenv install --dev  # install all project dependencies (including dev)

before_script:
  - yarn danger ci

script:
  - pipenv run black --check life tests
  - pipenv run pytest